Transform: AWS::Serverless-2016-10-31

Resources:
  DemoFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs16.x
      Handler: index.handler
      InlineCode: |
        exports.handler = () => Promise.resolve({ name: 'alola', author: 'balazs4', date: Date.now(), foobar: 42 })
      FunctionUrlConfig:
        AuthType: NONE

Outputs:
  DemoFunctionUrl:
    Value: !GetAtt 'DemoFunctionUrl.FunctionUrl'
